export interface TezosBlockChainInfo {
  baker: string,
  chainId: string,
  context: string,
  currentExpectedQuorum: number,
  endorsements: number,
  fitness: string,
  hash: string,
  level: number,
  metaCycle: number,
  metaCyclePosition: number,
  metaLevel: number,
  metaLevelPosition: number,
  metaVotingPeriod: number,
  metaVotingPeriodPosition: number,
  operationsHash: string,
  periodKind: string,
  predecessor: string,
  priority: number,
  proto: number,
  protocol: string,
  reward: number,
  signature: string,
  timestamp: number,
  validationPass: string
}
